
version: 2

models:
  - name: sales
    description: "This model represents sales data, including the date of sale, order ID, product ID, revenue, and quantity sold."
    columns:
      - name: date_date
        description: "The date of the sale."
        data_type: date
        tests:
          - not_null
      - name: orders_id
        description: "The unique identifier for each order."
        data_type: integer
        tests:
          - not_null
          - unique
      - name: pdt_id
        description: "The unique identifier for each product."
        data_type: integer
        tests:
          - not_null

  - name: product
    description: "This model represents product data, including product IDs and purchase prices."
    columns:
      - name: products_id
        description: "The unique identifier for each product."
        data_type: integer
        tests:
          - not_null
          - unique
      - name: purchase_price
        description: "The purchase price of the product."
        data_type: string
        tests:
          - not_null

  - name: ship
    description: "This model represents shipping data, including order IDs, shipping fees, and logistic costs."
    columns:
      - name: orders_id
        description: "The unique identifier for each order."
        data_type: integer
        tests:
          - not_null
      - name: shipping_fee
        description: "The fee charged for shipping."
        data_type: float
        tests:
          - not_null
      - name: shipping_fee_1
        description: "An additional fee for shipping, if applicable."
        data_type: float
        tests:
          - not_null
      - name: logCost
        description: "The logistic cost associated with shipping."
        data_type: float
        tests:
          - not_null
      - name: ship_cost
        description: "The cost incurred for shipping."
        data_type: string
        tests:
          - not_null